#!/usr/bin/env python

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

import test_lib

if __name__ == '__main__':
  tester_fn, testee_fn, target_test = sys.argv[:3]
  arglines = sys.argv[3:]
  sys.exit(test_lib.run_and_compare_arglines(
    arglines, testee_fn, target_test, differ=test_lib.diff_json_loosely))


