#!/usr/bin/env python3

import sys
import test_lib

if __name__ == '__main__':
  tester_fn, testee_fn, target_test = sys.argv[:3]
  arglines = sys.argv[3:]
  sys.exit(test_lib.run_and_compare_arglines(arglines, testee_fn, target_test))


